version: '3'
services:
  microauth:
    build:
      context: ./microAuth
    ports:
      - "7000:7000"
    environment:
      - NODE_ENV=production

  microinformation:
    build:
      context: ./microInformation-management
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production

  micromedical:
    build:
      context: ./microMedical-Appointment
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production

  apigateway:
    build:
      context: ./ApiGateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production